# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
    - Rscript -e 'covr::coveralls()'

before_deploy:
  - Rscript -e 'remotes::install_github("lockedatapublished/lockedatapkg")'
  - Rscript -e 'install.packages("pkgdown")'


deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
  skip_cleanup: true

after_success:
  - Rscript -e 'library(covr);coveralls(coverage = print(package_coverage(quiet = FALSE)))'

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

notifications:
  webhooks:
    urls:
      - https://api.netlify.com/build_hooks/5c48563f62f5b00171251b98
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
